services:
  frontend:
    image: frontend:latest
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    networks:
      - app-network
    profiles:
      - all
      - app
  backend:
    image: backend:latest
    container_name: backend
    build:
      context: ./api/app
    ports:
      - "3000:3000"
    environment:
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    networks:
      - app-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles:
      - all
      - app
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_BROWSER_REDIRECT_URL: http://minio.localhost
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - app-network
    profiles:
      - all
      - app
  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
      - minio
    networks:
      - app-network
    profiles:
      - all
      - app
      - proxy
  blender:
    image: blender:latest
    container_name: blender
    build:
      context: ./api/blender
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    networks:
      - app-network
    profiles:
      - tools
      - all
  hp3d:
    image: hp3d:latest
    container_name: hp3d
    build:
      context: ./api/hp3d
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    networks:
      - app-network
    profiles:
      - tools
      - all

volumes:
  minio-data:
    driver: local

networks:
  app-network:
    driver: bridge
